import {
	mdiArrowLeft as left,
	mdiArrowRight as right,
	mdiMagnify as search,
	mdiViewGridOutline as grid,
	mdiFormatListBulletedSquare as list,
	mdiFire as fire,
	mdiSpider as spider,
	mdiPlus as plus,
	mdiPlusCircle as plusCircle,
	mdiPlusCircleOutline as plusOutline,
	mdiClose as close,
	mdiFormatListText as listText,
	mdiChevronUp as arrowUp,
	mdiChevronDown as arrowDown,
	mdiDeleteOutline as delet,
	mdiPlaylistEdit as listEdit,
	mdiDrag as drag,
	mdiContentSave as save,
	mdiFormatFloatLeft as form,
	mdiFileDocumentEditOutline as draft,
	mdiDownload as download,
	mdiArrowCollapseAll as minify,
	mdiCodeJson as json,
	mdiDotsHorizontal as dotsHorizontal,
	mdiDotsVertical as dotsVertical,
	mdiFolder as folder,
	mdiStar as star,
	mdiServerRemove as serverRemove,
	mdiPuzzleEditOutline as puzzle,
	mdiCardTextOutline as card,
	mdiLinkVariant as link,
	mdiAccountCircleOutline as account,
	mdiLockOutline as lock,
	mdiEyeOutline as eye,
	mdiEyeOffOutline as eyeOff,
	mdiFacebook as facebook,
	mdiGoogle as google,
	mdiGithub as github,
	mdiLogoutVariant as logout,
	mdiLocationExit as logout2,
	mdiCog as settings,
	mdiRocketLaunchOutline as rocket,
	mdiViewDashboard as dashboard,
	mdiTruckFast as truck,
	mdiAccount as user,
	mdiAccountGroup as users,
	mdiWhiteBalanceSunny as sun,
	mdiThemeLightDark as theme,
	mdiAccountCowboyHat as employee,
	mdiDotsVertical as threeDot,
	mdiPencil as edit,
	mdiSync as sync,
	mdiRenameBox as name,
	mdiCellphoneAndroid as phone
} from '@mdi/js';

export default {
	left, search, grid, list, fire, draft, spider,
	plus, close, listText, form, star, arrowUp,
	arrowDown, delet, plusCircle, serverRemove,
	plusOutline, right, listEdit, drag, save,
	folder, download, minify, json, dotsHorizontal,
	dotsVertical, puzzle, card, link, account, lock,
	eye, eyeOff, facebook, google, github, logout,
	settings, logout2, rocket, dashboard, truck, user,
	users, sun, theme, employee, threeDot, edit, sync,
	name, phone
};
